/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ArticleList: typeof import('./components/ArticleList.vue')['default']
    ArticleView: typeof import('./components/ArticleView.vue')['default']
    BannerCarousel: typeof import('./components/BannerCarousel.vue')['default']
    CartListItem: typeof import('./components/CartListItem.vue')['default']
    CartMini: typeof import('./components/CartMini.vue')['default']
    CartMiniButton: typeof import('./components/CartMiniButton.vue')['default']
    CartTable: typeof import('./components/CartTable.vue')['default']
    CategoryList: typeof import('./components/CategoryList.vue')['default']
    DeliveryInfoCard: typeof import('./components/Checkout/DeliveryInfoCard.vue')['default']
    ImageLoader: typeof import('./components/ImageLoader.vue')['default']
    OrderDetails: typeof import('./components/OrderDetails.vue')['default']
    OrderItemsCard: typeof import('./components/Checkout/OrderItemsCard.vue')['default']
    OrderList: typeof import('./components/OrderList.vue')['default']
    OrderPaymentCard: typeof import('./components/Checkout/OrderPaymentCard.vue')['default']
    OrderSummaryCard: typeof import('./components/Checkout/OrderSummaryCard.vue')['default']
    ProductCard: typeof import('./components/Product/ProductCard.vue')['default']
    ProductCategoryList: typeof import('./components/Product/ProductCategoryList.vue')['default']
    ProductChooseList: typeof import('./components/Product/ProductChooseList.vue')['default']
    ProductColorChoose: typeof import('./components/Product/Choose/ProductColorChoose.vue')['default']
    ProductFilter: typeof import('./components/Product/ProductFilter.vue')['default']
    ProductGallery: typeof import('./components/Product/ProductGallery.vue')['default']
    ProductList: typeof import('./components/Product/ProductList.vue')['default']
    ProductMiniCard: typeof import('./components/Product/ProductMiniCard.vue')['default']
    ProductSizeChoose: typeof import('./components/Product/Choose/ProductSizeChoose.vue')['default']
    ProductSpecsList: typeof import('./components/Product/ProductSpecsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SbpPayment: typeof import('./components/Payment/SbpPayment.vue')['default']
    ScrollToTopBtn: typeof import('./components/ScrollToTopBtn.vue')['default']
    SearchField: typeof import('./components/SearchField.vue')['default']
    SmartImage: typeof import('./components/Bricks/SmartImage.vue')['default']
    SvgIcon: typeof import('./components/Bricks/SvgIcon.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}
