/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AboutPage': RouteRecordInfo<'/AboutPage', '/AboutPage', Record<never, never>, Record<never, never>>,
    '/ArticlePage': RouteRecordInfo<'/ArticlePage', '/ArticlePage', Record<never, never>, Record<never, never>>,
    '/CartPage': RouteRecordInfo<'/CartPage', '/CartPage', Record<never, never>, Record<never, never>>,
    '/CatalogPage': RouteRecordInfo<'/CatalogPage', '/CatalogPage', Record<never, never>, Record<never, never>>,
    '/CheckoutPage': RouteRecordInfo<'/CheckoutPage', '/CheckoutPage', Record<never, never>, Record<never, never>>,
    '/ContactsPage': RouteRecordInfo<'/ContactsPage', '/ContactsPage', Record<never, never>, Record<never, never>>,
    '/DeliveryPage': RouteRecordInfo<'/DeliveryPage', '/DeliveryPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/OrderPage': RouteRecordInfo<'/OrderPage', '/OrderPage', Record<never, never>, Record<never, never>>,
    '/OrderSuccessPage': RouteRecordInfo<'/OrderSuccessPage', '/OrderSuccessPage', Record<never, never>, Record<never, never>>,
    '/PaymentPage': RouteRecordInfo<'/PaymentPage', '/PaymentPage', Record<never, never>, Record<never, never>>,
    '/ProductPage': RouteRecordInfo<'/ProductPage', '/ProductPage', Record<never, never>, Record<never, never>>,
    '/ProfilePage': RouteRecordInfo<'/ProfilePage', '/ProfilePage', Record<never, never>, Record<never, never>>,
    '/RegisterPage': RouteRecordInfo<'/RegisterPage', '/RegisterPage', Record<never, never>, Record<never, never>>,
  }
}
