/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCreateDialog: typeof import('./components/categories/CategoryCreateDialog.vue')['default']
    CategoryEditDialog: typeof import('./components/categories/CategoryEditDialog.vue')['default']
    CategoryForm: typeof import('./components/categories/CategoryForm.vue')['default']
    DashboardStatCard: typeof import('./components/dashboard/DashboardStatCard.vue')['default']
    GalleryForm: typeof import('./components/gallery/GalleryForm.vue')['default']
    GallerySelect: typeof import('./components/gallery/GallerySelect.vue')['default']
    GallerySelectDialog: typeof import('./components/gallery/GallerySelectDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OrderCreateDialog: typeof import('./components/orders/OrderCreateDialog.vue')['default']
    OrderEditDialog: typeof import('./components/orders/OrderEditDialog.vue')['default']
    OrderFilterDialog: typeof import('./components/orders/OrderFilterDialog.vue')['default']
    OrderForm: typeof import('./components/orders/OrderForm.vue')['default']
    ProductCreateDialog: typeof import('./components/products/ProductCreateDialog.vue')['default']
    ProductEditDialog: typeof import('./components/products/ProductEditDialog.vue')['default']
    ProductForm: typeof import('./components/products/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecsForm: typeof import('./components/products/SpecsForm.vue')['default']
    UserCreateDialog: typeof import('./components/users/UserCreateDialog.vue')['default']
    UserDeleteDialog: typeof import('./components/users/UserDeleteDialog.vue')['default']
    UserEditDialog: typeof import('./components/users/UserEditDialog.vue')['default']
    UserForm: typeof import('./components/users/UserForm.vue')['default']
    UserInviteDialog: typeof import('./components/users/UserInviteDialog.vue')['default']
    UserResetPasswordDialog: typeof import('./components/users/UserResetPasswordDialog.vue')['default']
    UserRolesDialog: typeof import('./components/users/UserRolesDialog.vue')['default']
    VariantCreateDialog: typeof import('./components/products/VariantCreateDialog.vue')['default']
    VariantEditDialog: typeof import('./components/products/VariantEditDialog.vue')['default']
    VariantForm: typeof import('./components/products/VariantForm.vue')['default']
  }
}
