/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/BannerPage': RouteRecordInfo<'/BannerPage', '/BannerPage', Record<never, never>, Record<never, never>>,
    '/CategoriesPage': RouteRecordInfo<'/CategoriesPage', '/CategoriesPage', Record<never, never>, Record<never, never>>,
    '/DashboardPage': RouteRecordInfo<'/DashboardPage', '/DashboardPage', Record<never, never>, Record<never, never>>,
    '/GalleryPage': RouteRecordInfo<'/GalleryPage', '/GalleryPage', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/OrdersPage': RouteRecordInfo<'/OrdersPage', '/OrdersPage', Record<never, never>, Record<never, never>>,
    '/ProductsPage': RouteRecordInfo<'/ProductsPage', '/ProductsPage', Record<never, never>, Record<never, never>>,
    '/TagPage': RouteRecordInfo<'/TagPage', '/TagPage', Record<never, never>, Record<never, never>>,
    '/UsersPage': RouteRecordInfo<'/UsersPage', '/UsersPage', Record<never, never>, Record<never, never>>,
  }
}
